
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/academia?useTimezone=UTC&useLegacyDate
    username: juliana
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true

